spring:
  application:
    name: Spring Core Demo Application - PF9
  profiles:
    active: dev
my:
  custom:
    property: 10
myproperties:
  threadPool: 5
  email: example@development.com
  servers:
    - www.abc.dev.com
    - www.xyz.dev.com
