spring:
  application:
    name: Spring Core Demo Application - PF9
my:
  custom:
    property: 10
myproperties:
  threadPool: 40
  email: example@development.com
  servers:
    - www.abc.dev.com
    - www.xyz.dev.com
